/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "erbvhhhxftbmvxfrmnof"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVyYnZoaGh4ZnRibXZ4ZnJtbm9mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4OTg0MDUsImV4cCI6MjA3MjQ3NDQwNX0.bsTXYn-pfro0RzK09f-kk2grY9No1PktWQISPgbhGk0"